/**
 * Audit logging system
 */
import { IAuditEntry } from '@erp/types';
import logger from '../security/logger';

export interface AuditLogInput {
  organizationId: string;
  userId: string;
  action: 'create' | 'read' | 'update' | 'delete';
  entity: string;
  entityId: string;
  changes?: Record<string, unknown>;
  ipAddress?: string;
  requestId: string;
}

/**
 * Log an audit entry
 * TODO: Store in database
 */
export async function logAudit(input: AuditLogInput): Promise<void> {
  const entry: IAuditEntry = {
    _id: '', // Generated by MongoDB
    organizationId: input.organizationId,
    userId: input.userId,
    action: input.action,
    entity: input.entity,
    entityId: input.entityId,
    changes: input.changes,
    timestamp: new Date(),
    ipAddress: input.ipAddress,
    requestId: input.requestId,
  };

  logger.info({
    type: 'audit',
    ...entry,
  });

  // TODO: Save to audit_logs collection
}

export * from './audit';
