/** Demo catalog: seed input only. Nothing in the mobile app imports these records. */
export const DEMO_PREFIX = 'ERP-SC DEMO v1';
export const CATEGORY_LABELS = ['Dulces','Chocolates','Gomitas','Paletas','Caramelos','Botanas','Bebidas','Galletas','Confitería','Temporada'];
const catalog = [
 ['Dulces', [['Mazapán de cacahuate',5],['Pulparindo de tamarindo',4],['Dulce de tamarindo en vasito',8],['Obleas con cajeta',10],['Alegría de amaranto',12],['Cocada de leche',9],['Dulce de leche en barra',8],['Palanqueta de cacahuate',13],['Ate de guayaba individual',10],['Rollo de guayaba con nuez',18]]],
 ['Chocolates', [['Chocolate con leche 25 g',15],['Chocolate amargo 30 g',22],['Chocolate blanco 25 g',18],['Chocolate con almendras',25],['Chocolate con cacahuate',16],['Chocolate relleno de caramelo',17],['Chocolate con galleta',14],['Monedas de chocolate bolsa',24],['Trufas de chocolate bolsa',35],['Chocolate con arroz inflado',12]]],
 ['Gomitas', [['Gomitas de ositos 100 g',18],['Gomitas enchiladas 100 g',20],['Gomitas de gusanos 100 g',18],['Gomitas de manguito 100 g',22],['Gomitas de sandía 100 g',19],['Gomitas de cola 100 g',18],['Gomitas de aros de durazno',20],['Gomitas de frutas mixtas',19],['Gomitas de corazones',18],['Gomitas ácidas surtidas',22]]],
 ['Paletas', [['Paleta de caramelo',3],['Paleta de mango con chile',5],['Paleta de sandía con chile',5],['Paleta de cereza',4],['Paleta de tamarindo',5],['Paleta de fresa con crema',5],['Paleta de chocolate',8],['Paleta de cajeta',6],['Paleta de malvavisco',10],['Paleta espiral multicolor',12]]],
 ['Caramelos', [['Caramelos de menta 100 g',16],['Caramelos de café 100 g',18],['Caramelos de leche 100 g',17],['Caramelos de miel 100 g',19],['Caramelos de frutas 100 g',15],['Caramelos de eucalipto',17],['Caramelos suaves de vainilla',20],['Caramelos de coco',18],['Caramelos de limón',16],['Caramelos rellenos de chocolate',23]]],
 ['Botanas', [['Papas saladas 45 g',17],['Papas con limón 45 g',18],['Papas adobadas 45 g',18],['Cacahuates japoneses 80 g',16],['Cacahuates enchilados 80 g',17],['Cacahuates salados 80 g',15],['Churritos con chile 80 g',12],['Frituras de maíz 60 g',15],['Habitas enchiladas 80 g',18],['Semillas de girasol 60 g',14]]],
 ['Bebidas', [['Agua natural 600 ml',12],['Agua mineral 600 ml',18],['Refresco de cola 355 ml',20],['Refresco de naranja 355 ml',18],['Refresco de limón 355 ml',18],['Jugo de mango 250 ml',14],['Jugo de manzana 250 ml',14],['Néctar de durazno 250 ml',15],['Bebida de chocolate 250 ml',18],['Agua de jamaica 500 ml',20]]],
 ['Galletas', [['Galletas de vainilla 90 g',15],['Galletas de chocolate 90 g',17],['Galletas con chispas 90 g',20],['Galletas de avena 90 g',19],['Galletas rellenas de fresa',18],['Galletas rellenas de limón',18],['Galletas saladas 80 g',14],['Galletas de coco 90 g',19],['Galletas de animalitos 100 g',13],['Barquillos de chocolate 80 g',22]]],
 ['Confitería', [['Chicles de hierbabuena',5],['Chicles de frutas',5],['Chicles de canela',6],['Malvaviscos blancos 100 g',19],['Malvaviscos mini 100 g',20],['Malvaviscos con chocolate',24],['Grageas de chocolate 100 g',27],['Lunetas de colores 50 g',16],['Merengues surtidos bolsa',20],['Algodón de azúcar en bolsa',18]]],
 ['Temporada', [['Calaverita de azúcar pequeña',25],['Calaverita de chocolate pequeña',35],['Bolsita de dulces para posada',30],['Bastones de caramelo navideños',12],['Huevitos de chocolate surtidos',28],['Corazones de chocolate regalo',35],['Dulces surtidos para piñata',45],['Gomitas Halloween 100 g',24],['Bombones navideños bolsa',28],['Canastita de dulces de temporada',65]]],
];
export const DEMO_PRODUCTS = catalog.flatMap(([category, rows]) => rows.map(([name, price]) => ({category,name,price}))).map((item,index) => ({
 code: 'DEMO-DUL-'+String(index+1).padStart(3,'0'), name:item.name,
 description:`Producto de demostración de dulcería mexicana. Clasificación comercial: ${item.category}. Precio expresado en MXN.`,
 unit:item.category==='Bebidas'?'botella':['Gomitas','Caramelos','Botanas','Galletas'].includes(item.category)?'bolsa':'pieza',
 price:item.price,cost:Math.round(item.price*0.58*100)/100,minStock:5,
}));
const names=['María Fernanda López','José Luis Hernández','Ana Sofía García','Juan Carlos Martínez','Guadalupe Rodríguez','Miguel Ángel Pérez','Rosa Elena Sánchez','Luis Alberto Ramírez','Claudia Patricia Torres','Carlos Eduardo Flores','Patricia Isabel Gómez','Ricardo Antonio Díaz','Verónica Cruz Morales','Francisco Javier Reyes','Daniela Salazar Ortiz','Alejandro Mendoza Ruiz','Mónica Jiménez Vargas','Sergio Castillo Romero','Laura Beatriz Navarro','Jorge Manuel Aguilar'];
export const DEMO_CUSTOMERS=names.map((name,i)=>({code:'DEMO-CLI-'+String(i+1).padStart(3,'0'),name,type:'person',email:`cliente${String(i+1).padStart(2,'0')}@demo.example`,phone:String(5501000000+i),address:{street:`Calle Demo ${i+1}`,city:'Ciudad de México',region:'CDMX',country:'MX'}}));
const suppliers=['Distribuidora Dulce México','Chocolates Sierra del Sur','Gomitas del Valle','Paletería Los Colores','Caramelos La Tradición','Botanas El Buen Sabor','Bebidas del Centro','Galletas La Espiga','Confitería Azúcar y Miel','Dulces de Temporada México','Tamarindos La Huerta','Cacahuates San Juan','Mazapanes La Familia','Empaques para Dulcería','Distribuciones La Piñata'];
export const DEMO_SUPPLIERS=suppliers.map((name,i)=>({code:'DEMO-PRO-'+String(i+1).padStart(3,'0'),name,email:`proveedor${String(i+1).padStart(2,'0')}@demo.example`,phone:String(5581000000+i),address:{street:`Avenida Demo ${i+1}`,city:'Ciudad de México',region:'CDMX',country:'MX'}}));
export const DEMO_EXPENSES=[['Renta del local',4000],['Electricidad',1250],['Agua',350],['Transporte de mercancía',700],['Papelería',280],['Mantenimiento',900]];
export const INITIAL_QUANTITIES=[10,25,50,100,200];
